apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-deployment
  namespace: cdap
spec:
  selector:
    matchLabels:
      app: orderapi
  replicas: 1
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi
        image: npsan0330/orderapi:v3
        ports:
        - containerPort: 5001
        env:
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: cdap-config
              key: rabbit-mq-host
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: cdap-config
              key: rabbit-mq-port
        - name: RABBIT_MQ_USER
          valueFrom:
            configMapKeyRef:
              name: cdap-config
              key: rabbit-mq-user
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cdap-config
              key: rabbit-mq-password
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
  namespace: cdap
spec:
  type: NodePort
  selector:
    app: orderapi
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30101
